# Generated by Django 4.2.16 on 2024-09-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author_alter_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publications',
            new_name='post',
        ),
    ]
